# Generated by Django 5.2.5 on 2025-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantTopic',
            fields=[
                ('important_topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=20)),
                ('exam_type', models.CharField(choices=[('cat1', 'CAT I'), ('cat2', 'CAT II'), ('fat', 'FAT')], max_length=20)),
                ('faculty_name', models.CharField(max_length=50)),
                ('file_choosen', models.FileField(upload_to='ImportantTopics/')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=20)),
                ('exam_type', models.CharField(choices=[('cat1', 'CAT I'), ('cat2', 'CAT II'), ('fat', 'FAT')], max_length=20)),
                ('faculty_name', models.CharField(max_length=50)),
                ('file_choosen', models.FileField(upload_to='Materials/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('question_paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=20)),
                ('exam_type', models.CharField(choices=[('cat1', 'CAT I'), ('cat2', 'CAT II'), ('fat', 'FAT')], max_length=20)),
                ('semester', models.CharField(choices=[('fall', 'Fall Sem'), ('win', 'Win Sem'), ('others', 'Others')], max_length=20)),
                ('file_choosen', models.FileField(upload_to='QuestionPapers/')),
            ],
        ),
    ]
