# Generated by Django 5.2.5 on 2025-09-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportantTopic',
            new_name='ImportantTopics',
        ),
        migrations.RenameModel(
            old_name='Material',
            new_name='Materials',
        ),
        migrations.RenameModel(
            old_name='QuestionPaper',
            new_name='QuestionPapers',
        ),
    ]
