# Generated by Django 5.2.5 on 2025-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_rename_importanttopic_importanttopics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importanttopics',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
