# Generated by Django 5.2.5 on 2025-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_importanttopics_user_materials_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpapers',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
