# Generated by Django 5.2.5 on 2025-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_questionpapers_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='importanttopics',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materials',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionpapers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
