# Generated by Django 5.2.5 on 2025-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_importanttopics_is_deleted_materials_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importanttopics',
            name='exam_type',
            field=models.CharField(choices=[('CAT I', 'CAT I'), ('CAT II', 'CAT II'), ('FAT', 'FAT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='materials',
            name='exam_type',
            field=models.CharField(choices=[('CAT I', 'CAT I'), ('CAT II', 'CAT II'), ('FAT', 'FAT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpapers',
            name='exam_type',
            field=models.CharField(choices=[('CAT I', 'CAT I'), ('CAT II', 'CAT II'), ('FAT', 'FAT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpapers',
            name='semester',
            field=models.CharField(choices=[('Fall Sem', 'Fall Sem'), ('Win Sem', 'Win Sem'), ('Others', 'Others')], max_length=20),
        ),
    ]
