# Generated by Django 5.2.5 on 2025-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_importanttopics_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpapers',
            name='semester',
            field=models.CharField(choices=[('FALL SEM', 'FALL SEM'), ('WIN SEM', 'WIN SEM'), ('Others', 'Others')], max_length=20),
        ),
    ]
