# Generated by Django 5.2.5 on 2025-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_alter_questionpapers_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='importanttopics',
            name='important_topic_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='study_material_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpapers',
            name='exam_slot',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpapers',
            name='question_paper_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
