# Generated by Django 5.2.5 on 2025-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_importanttopics_important_topic_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='materials',
            name='topic_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
