# Generated by Django 5.2.5 on 2026-05-30 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('faculty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100, unique=True)),
                ('faculty_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'faculties',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_password_hash', models.CharField(max_length=255)),
                ('user_is_active', models.BooleanField(default=True)),
                ('user_last_login_at', models.DateTimeField(default=None, null=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_updated_at', models.DateTimeField(auto_now=True)),
                ('user_deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('question_paper_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_paper_title', models.CharField(max_length=100)),
                ('question_paper_exam_slot', models.CharField(max_length=10)),
                ('question_paper_exam_type', models.CharField(choices=[('CAT I', 'CAT I'), ('CAT II', 'CAT II'), ('FAT', 'FAT')], max_length=20)),
                ('question_paper_semester', models.CharField(choices=[('FALL SEM', 'FALL SEM'), ('WIN SEM', 'WIN SEM'), ('Others', 'Others')], max_length=20)),
                ('question_paper_year', models.IntegerField(default=2017)),
                ('question_paper_file_path', models.CharField(max_length=1024)),
                ('question_paper_created_at', models.DateTimeField(auto_now_add=True)),
                ('question_paper_updated_at', models.DateTimeField(auto_now=True)),
                ('question_paper_deleted_at', models.DateTimeField(default=None, null=True)),
                ('fk_subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.PROTECT, related_name='question_papers', to='client_model_app.subjects')),
                ('fk_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='client_model_app.userinfo')),
            ],
            options={
                'db_table': 'question_papers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_title', models.CharField(max_length=100)),
                ('material_topic_type', models.CharField(max_length=50)),
                ('material_file_path', models.CharField(max_length=1024)),
                ('material_created_at', models.DateTimeField(auto_now_add=True)),
                ('material_updated_at', models.DateTimeField(auto_now=True)),
                ('material_deleted_at', models.DateTimeField(default=None, null=True)),
                ('fk_faculty', models.ForeignKey(blank=True, db_column='faculty_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='client_model_app.faculties')),
                ('fk_subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='client_model_app.subjects')),
                ('fk_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='client_model_app.userinfo')),
            ],
            options={
                'db_table': 'materials',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImportantTopics',
            fields=[
                ('important_topic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('important_topic_title', models.CharField(max_length=100)),
                ('important_topic_exam_type', models.CharField(choices=[('CAT I', 'CAT I'), ('CAT II', 'CAT II'), ('FAT', 'FAT')], max_length=20)),
                ('important_topic_file_path', models.CharField(max_length=1024)),
                ('important_topic_created_at', models.DateTimeField(auto_now_add=True)),
                ('important_topic_updated_at', models.DateTimeField(auto_now=True)),
                ('important_topic_deleted_at', models.DateTimeField(default=None, null=True)),
                ('fk_faculty', models.ForeignKey(blank=True, db_column='faculty_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_topics', to='client_model_app.faculties')),
                ('fk_subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.PROTECT, related_name='important_topics', to='client_model_app.subjects')),
                ('fk_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='important_topics', to='client_model_app.userinfo')),
            ],
            options={
                'db_table': 'important_topics',
                'managed': True,
            },
        ),
    ]
