# Generated by Django 5.1.15 on 2026-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_model_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpapers',
            name='question_paper_exam_slot',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D1', 'D1'), ('D2', 'D2'), ('E1', 'E1'), ('E2', 'E2'), ('F1', 'F1'), ('F2', 'F2'), ('G1', 'G1'), ('G2', 'G2')], max_length=2),
        ),
    ]
